backend:
    name: git-gateway
    branch: master

  
media_folder: "src/images/homes"
public_folder: "/images/homes"


collections:
  - name:  "inventory"
    label:  "Inventory"
    folder:  "src/inventory"
    create:  true
    slug:  "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - { name: "purpose", label: "Purpose",  widget: "string", identifier: true }
      - { name: "coveredArea", label: "Covered Area", widget: "number" }
      - { name: "price", label: "Price", widget: "string" }
      - { name: "bedrooms", label: "Bedrooms", widget: "number" }
      - { name: "tags", label: "Tags", widget: "list", default: ["listing"] }
      - { name: "baths", label: "Baths", widget: "number" }
      - { name: "image", label: "Image", widget: "image"  }
      - { name: "location", label: "Location", widget: "string" }
      - { name: "description", label: "Description", widget: "markdown" }
